site_name: My School HPC Guide
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs      # Enables the top horizontal menu
    - navigation.sections  # (Optional) Makes the left sidebar look grouped
    - navigation.expand    # (Optional) Keeps the left menu expanded by default
    - search.share    # Built-in search bar

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
    - Overview: gettingstarted/overview.md
    - Logging in: gettingstarted/loggingin.md
    - Copying Files: gettingstarted/copyingfiles.md
  - Resources: 
    - Cluster Info: resources/clusterinfo.md
    - Monitoring Software: resources/monitoring.md
  - Software: 
    - Loading Modules: software/loading.md
    - Compiling Software: software/compiling.md
    - Installed Software: software/installed.md
  - Documentation: 
    - Slurm Tutorial: documentation/slurm.md
  - Tutorials:
    - Tensorflow CPU: tutorials/tensorcpu.md
    - Tensorflow GPU: tutorials/tensorgpu.md
    - PyTorch: tutorials/pytorch.md
  - Help: help.md
