site_name: My School HPC Guide
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs      # Enables the top horizontal menu
    - navigation.sections  # (Optional) Makes the left sidebar look grouped
    - navigation.expand    # (Optional) Keeps the left menu expanded by default
    - search.share    # Built-in search bar

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
    - Overview: overview.md
    - Logging in: loggingin.md
    - Copying Files: copyingfiles.md
  - Resources: 
    - Cluster Info: clusterinfo.md
    - Monitoring Software: monitoring.md
  - Software: 
    - Loading Modules: loading.md
    - Compiling Software: compiling.md
    - Installed Software: installed.md
  - Documentation: 
    - Slurm Tutorial: slurm.md
  - Tutorials:
    - Tensorflow CPU: tensorcpu.md
    - Tensorflow GPU: tensorgpu.md
    - PyTorch: pytorch.md
  - Help: help.md
